include:
  - path: docker/compose.db.yml
    project_directory: .
    env_file: docker/db.env
  - path: docker/compose.db-test.yml
    project_directory: .
    env_file: docker/db-test.env
  - path: docker/compose.api.yml
    project_directory: .
