"""add delivery cycles

Revision ID: 41095acbf894
Revises: c87ec48cef85
Create Date: 2026-09-11 19:04:35.892946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41095acbf894'
down_revision: Union[str, Sequence[str], None] = 'c87ec48cef85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('delivery_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_eggs', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='deliverycyclestatus', native_enum=False, length=16), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_cycles_provider_id'), 'delivery_cycles', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_cycles_provider_id'), table_name='delivery_cycles')
    op.drop_table('delivery_cycles')
    # ### end Alembic commands ###
